### ISSUE TITLE
x68 support

### ISSUE THREAD

**Issue by passsy** [HQarroum/android-mdns#1]
This lib does only support `armeabi`. Could you please add the binary for the `x68` architecture?

**Comment by HQarroum** [comment]
Hi, thanks for your interest ! Yes I can compile the library for x86, however my goal is to simply have the source code hosted on Github and a .aar embedding the native binaries associated with diffenrent platforms on Java central. I'll let this issue open until I have done just that.

**Comment by osayilgan** [comment]
@HQarroum any updates?

**Comment by HQarroum** [comment]
Yes. It turns out this implementation by Apple, in fact the wrapper with the JNI code, breaks on very recent versions of Android (6+) running the ART runtime. And we haven't been able to fix that properly. As a result, I will shortly replace this project by a new generic wrapper around the Android NSD service + a version of jMDNS which has proven to be working properly on early Android version (pre-NSD).

I'll include x86 builds of jMDNS, and if you want this library to run it on the Android x86 project, it will work since they already ported the Android NSD internal service.

**Comment by osayilgan** [comment]
I basically need arm, arm64, x86 and x86_64. I'm not urgently interested in early Android releases for now. Since native NSD service has the TXT record issue, I need to resolve that information.
